name: clepy
description: App de Aluguel

publish_to: 'Clepy team'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  flutter_bloc: ^8.0.1
  card_swiper: ^2.0.3
  equatable: ^2.0.3
  flutter_multi_select_items: ^0.4.0  
  firebase_core: ^1.11.0
  firebase_storage: ^10.3.2
  flutter_svg: ^1.1.0
  simple_animations: ^4.0.2
  scrollable_positioned_list: ^0.3.2
  url_launcher: ^6.1.3


  clepy_ui:
    path: packages/clepy_ui
  clepy_caches:
    path: packages/clepy_caches
  domain: 
    path: packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3
  modular_test: ^2.0.0
  test_api: ^0.4.9
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  image_picker: ^0.8.5+3
  hexcolor: ^2.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imagens/golfinho.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/
