name: clepy_ui
description: design package
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #pacotes visuais
  flutter_rating_bar: ^4.0.0
  fancy_drawer: ^2.0.0
  dot_navigation_bar: ^1.0.1+4
  flutter_modular: ^5.0.2

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
